# Dockerfile para desarrollo (hot reload y dependencias)
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala todas las dependencias (incluyendo dev)
RUN npm install

# Copia el resto del código fuente
COPY . .

# Genera el cliente de Prisma
RUN npx prisma generate

# Expone el puerto de la app
EXPOSE 3000


# Comando para desarrollo con hot reload
CMD ["npm", "run", "start:dev"]
